baseURL = 'http://brianburrous.com/'
languageCode = 'en-us'
title = 'Brian Burrous'
theme = "lekh"

[params]
Name = "Brian Burrous"
About = "Recent mechanical engineering grad, with experience in robotics, controls, and manufacturing. I studied mechanical engineering because... I'm interested in ..."
Email = "brburrous@g.ucla.edu"
Resume = "resume.pdf" # Add the filename with file extension.
PostLimit = 4 # Sets the number of posts to display on the front page
GoatCounterCode = ""

[[params.profiles]]
name = "GitHub"
url = "https://github.com/brburrous"

[[params.profiles]]
name = "Twitter"
url = "https://twitter.com/brian_burrous"


[[params.profiles]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/brian-burrous/"


